### ISSUE TITLE
user-agent header not collected

### ISSUE THREAD

**Issue by fastfiveoh** [iopipe/iopipe-js-trace#32]
It appears that the user-agent header is not being collected by the IOpipe library when it should be.

Tested on the latest @iopipe/iopipe , 1.15.0 displayed in IOpipe dashboard.  Environment is Node v8.10.0, requestor was axios library.

**Comment by fastfiveoh** [comment]
This was in conjunction with the use of the Axios library, which when doing an `await axios.get(url)`, did not return the user-agent header when Axios states that is default behavior.

**Comment by adjohn** [comment]
I do see it being collected in Python fwiw:
![screen shot 2018-11-07 at 2 35 35 pm](https://user-images.githubusercontent.com/168944/48165433-6dd02a80-e29a-11e8-9416-fed3fdb40fb9.png)

**Comment by pselle** [comment]
After some investigation, it seems that this may be a simple case where axios sends the header as `User-Agent` and we're looking for `user-agent`. We should be normalizing headers/shouldn't lose this.

**Comment by mrickard** [comment]
User-Agent header for the node agent was restored in https://github.com/iopipe/iopipe-js-trace/releases/tag/v1.5.1
