### ISSUE TITLE
AutoHTTP: request headers not captured on timeout

### ISSUE THREAD

**Issue by ewindisch** [iopipe/iopipe-js-trace#41]
I have a function that is timing out. The beginning of traces happens, but request headers are not captured.

Example from my project where this is happening:
https://dashboard.iopipe.com/project/a402e437-0722-44d9-8e27-c0ac276381e4/functions/arn:aws:lambda:us-east-1:666468248896:function:demo-tracing-overflow-dev-hello/invocation/AWjjf0I0QnmGDxYo6w3D#tab=Tracing&timeframe=1h

**Comment by ewindisch** [comment]
![screenshot](https://www.dropbox.com/s/l1rkzgh1ghvkmzr/Screen%20Shot%202019-02-12%20at%204.03.23%20PM.png?dl=0)

**Comment by mrickard** [comment]
AutoHTTP has a double-filtering structure: first a list of default request/response keys to record, of which we only whitelist user-agent. Then there's another step of filtering keys that also filters user-agent, so we're not actually recording any request headers, it looks like, whether or not a request has timed out. (If anyone sees invocations other than my tests that contain request headers, please let me know!)  

The filtering makes sense--obviously authentication-related headers should be filtered out, but obviously we need to include some headers.  Does anyone have preferences on what should be included beyond, say, these?

- User-Agent
- Content-Length
- Content-Type
- Via
- Warning
- Expect
- Accept
- Accept-Encoding
- Cache-Control

I'd be inclined not to include Referer on the chance that the referring URL might contain sensitive data. Similar with Forwarded or Content-MD5.

**Comment by kolanos** [comment]
The Python agent limited the default headers collected to these: https://github.com/iopipe/iopipe-python/pull/326

**Comment by mrickard** [comment]
Working timeout req headers on this test trace: https://dashboard.iopipe.com/project/97ad3ff5-506f-4072-a2a8-06ac9a7c901c/functions/arn:aws:lambda:local:0:function:timeouttest-dev-testHttpTimeout/invocation/AWy3d6clCcgi2Zl5D1tF#tab=Tracing
