### ISSUE TITLE
AutoHTTP: All request headers collected on timeout, no request headers for a non timeout

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-js-trace#49]
Here are two invocations, one had a timeout due to a timed out call to Kinesis, the retry was a success.  The timed out call contains *all* the request headers, including security headers.  The successful call contains no request headers for the kinesis call. 

Example invocations: 
The timed out invocation: 
https://dashboard.iopipe.com/project/d02087b2-71a3-4260-a984-9dfa9ae8a670/functions/arn:aws:lambda:us-east-1:554407330061:function:aws-elasticsearch-write-prod-es55-us-east-1/invocation/AWtRihQZRLLtp5j718pR#tab=Tracing

The successful retry: 
https://dashboard.iopipe.com/project/d02087b2-71a3-4260-a984-9dfa9ae8a670/functions/arn:aws:lambda:us-east-1:554407330061:function:aws-elasticsearch-write-prod-es55-us-east-1/invocation/AWtRihgmE5SfY795boWW#tab=Tracing&timeframe=24h

**Comment by mrickard** [comment]
Closing; resolved with #62
