### ISSUE TITLE
v1.5.0 breaks Rollup with CommonJS Plugin

### ISSUE THREAD

**Issue by ryansolid** [iopipe/iopipe-js-trace#61]
When bundling with Rollup, the CommonJS plugin(https://github.com/rollup/rollup-plugin-commonjs) cannot handle the dynamic require used to load plugins. To my knowledge, there is no way to work around this in Rollup.

**Comment by mrickard** [comment]
@ryansolid Thank you for the report!  We have a couple paths for a fix.  Which version of Node are you using?

**Comment by ryansolid** [comment]
Currently using Node 8. Although Node 10 could be serviceable. We are attempting to use IOPipe on Lambda Edge which doesn't support Layers, and for Viewer Request Functions need to be no larger than 2mb, so bundling is a must. Webpack obviously is an option since it knows how to handle this scenario, but we've been using Rollup to date. Not using Serverless or any framework currently. Just bundling stuff up ourselves. For now we locked versions which seems to be working.

Thanks for any assistance.

**Comment by mrickard** [comment]
@ryansolid Thank you for the context!  If you're currently using iopipe-js-core with Node 8 (and I'd think you are), I can prioritize a Node-8-friendly fix.

**Comment by ryansolid** [comment]
Yes we are using that. I reported against this repo since the culprit is line 122 of src/index.js of this repository. Anyway, thank you.

**Comment by mrickard** [comment]
@ryansolid I have a [PR](https://github.com/iopipe/iopipe-js-trace/pull/63/files) that seems to resolve this in my tests, but I'd like to hear if it works in your environment.  Mind taking a look?

**Comment by ryansolid** [comment]
Thank you. I tried to npm installed (just straight from the git repo) and noticed that I only get the dist folder which is already compiled down to CJS. The problem there is that the dynamic require is still there since your dynamic import gets compiled down to this:
```js
const load = plugin => Promise.resolve().then(() => require(`./plugins/${plugin}` ));
```

Which then my rollup converts to:
```js
const load = plugin => Promise.resolve().then(() => commonjsRequire());
```
Which is their way of triggering the error.  I'm pretty sure if I was dealing with the ES6 src it would work but I don't believe it's packaged in. I'd have no issue aliasing it and doing the conversion during my build were it there. A bit awkward I suppose since it makes sense for the library to ship commonjs as that is what works with Node.
